# Generated by Django 6.0.3 on 2026-03-20 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_automations', '0004_alter_horillaautomation_model'),
        ('horilla_core', '0012_alter_fieldpermission_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horillaautomation',
            name='schedule_date_field',
            field=models.CharField(blank=True, help_text="The date field on the record to schedule around (e.g., 'close_date', 'due_date'). Required for scheduled automations.", max_length=100, verbose_name='Target Date Field'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='schedule_offset_amount',
            field=models.IntegerField(blank=True, help_text='How many days/weeks/months away from the Target Date.\nUse 0 to send on the same day.', null=True, verbose_name='Adjust By'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='schedule_offset_direction',
            field=models.CharField(blank=True, choices=[('before', 'Before'), ('after', 'After')], help_text='Before = send earlier than the Target Date.\nAfter = send later than the Target Date.', max_length=10, verbose_name='Timing'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='schedule_offset_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], help_text='Choose Days, Weeks, or Months.', max_length=16, verbose_name='Offset Unit'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='schedule_run_time',
            field=models.TimeField(blank=True, help_text='Optional. Leave empty to run whenever the scheduler runs.', null=True, verbose_name='Run Time'),
        ),
        migrations.AlterField(
            model_name='automationcondition',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('greater_than', 'Greater Than'), ('greater_than_equal', 'Greater Than or Equal'), ('less_than', 'Less Than'), ('less_than_equal', 'Less Than or Equal'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('exact', 'Equals'), ('gt', 'After'), ('lt', 'Before'), ('between', 'Between'), ('isnull', 'Is empty'), ('isnotnull', 'Is not empty')], max_length=50, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='horillaautomation',
            name='trigger',
            field=models.CharField(choices=[('on_create', 'On Create'), ('on_update', 'On Update'), ('on_create_or_update', 'Both Create and Update'), ('on_delete', 'On Delete'), ('scheduled', 'Scheduled (time-based)')], max_length=20, verbose_name='Trigger'),
        ),
        migrations.CreateModel(
            name='AutomationRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('object_id', models.CharField(max_length=64, verbose_name='Object ID')),
                ('run_date', models.DateField(verbose_name='Run Date')),
                ('scheduled_for', models.DateField(blank=True, help_text='The instance date value that matched when this automation executed.', null=True, verbose_name='Scheduled For')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='horilla_automations.horillaautomation', verbose_name='Automation')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horilla_core.horillacontenttype', verbose_name='Content Type')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Automation Run Log',
                'verbose_name_plural': 'Automation Run Logs',
                'unique_together': {('automation', 'content_type', 'object_id', 'scheduled_for')},
            },
        ),
    ]
