# Generated by Django 6.0 on 2026-02-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_core', '0006_alter_kanbangroupby_model_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horillauser',
            unique_together={('company', 'username', 'role')},
        ),
    ]
