# Generated by Django 6.0.3 on 2026-04-10 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_core', '0012_alter_fieldpermission_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holiday',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
