# Generated by Django 6.0.3 on 2026-04-03 11:12

import django.db.models.deletion
import horilla.registry.limiters
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horilla_core', '0012_alter_fieldpermission_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalProcessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('rule_config', models.JSONField(blank=True, default=dict, help_text='Per-rule JSON: approval_actions, rejection_actions, record_modification, process_admins (or rule-level admin overrides).')),
                ('order', models.PositiveIntegerField(default=1, help_text='Sequence of this rule within the process.', verbose_name='Order')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Approval process rule',
                'verbose_name_plural': 'Approval process rules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('greater_than', 'Greater Than'), ('greater_than_equal', 'Greater Than or Equal'), ('less_than', 'Less Than'), ('less_than_equal', 'Less Than or Equal'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('exact', 'Equals'), ('gt', 'After'), ('lt', 'Before'), ('between', 'Between'), ('isnull', 'Is empty'), ('isnotnull', 'Is not empty'), ('icontains', 'Contains'), ('ne', 'Not Equals'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('logical_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3, verbose_name='Logical Operator')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('approval_process_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='approvals.approvalprocessrule', verbose_name='Process rule')),
            ],
            options={
                'verbose_name': 'Approval Condition',
                'verbose_name_plural': 'Approval Conditions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True)),
                ('trigger_on_create', models.BooleanField(default=True, help_text='Run this process when a new record is created.', verbose_name='When record is created')),
                ('trigger_on_edit', models.BooleanField(default=False, help_text='Run this process when a record is edited.', verbose_name='When record is edited')),
                ('process_config', models.JSONField(blank=True, default=dict, help_text='Optional process-wide defaults. Prefer rule_config on each process rule.')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('model', models.ForeignKey(help_text='Model this process applies to.', limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('approval_models'), on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='horilla_core.horillacontenttype', verbose_name='Module')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Approval process',
                'verbose_name_plural': 'Approval processes',
            },
        ),
        migrations.AddField(
            model_name='approvalprocessrule',
            name='approval_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_rules', to='approvals.approvalrule', verbose_name='Approval process'),
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.PositiveIntegerField(help_text='Sequence order of this step within the rule.')),
                ('approver_type', models.CharField(choices=[('user', 'Specific user'), ('owner_manager', 'Manager of record owner'), ('role', 'Role')], default='user', max_length=32)),
                ('role_identifier', models.CharField(blank=True, help_text='Identifier for the role (implementation-specific).', max_length=255)),
                ('approval_process_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalprocessrule')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps_as_user', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Approval step',
                'verbose_name_plural': 'Approval steps',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('object_id', models.CharField(help_text='Primary key of the target object, stored as string.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16, verbose_name='Status')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('approval_models'), on_delete=django.db.models.deletion.CASCADE, related_name='approval_instances', to='horilla_core.horillacontenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approvals.approvalrule', verbose_name='Rule')),
                ('current_step', models.ForeignKey(blank=True, help_text='The step currently awaiting decision, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_instances', to='approvals.approvalstep')),
            ],
            options={
                'verbose_name': 'Approval instance',
                'verbose_name_plural': 'Approval instances',
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalstep')),
            ],
            options={
                'verbose_name': 'Approval decision',
                'verbose_name_plural': 'Approval decisions',
                'ordering': ['-decided_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalprocessrule',
            constraint=models.UniqueConstraint(fields=('approval_process', 'order'), name='approvals_processrule_process_order_uniq'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='approvals_a_content_03463d_idx'),
        ),
    ]
