# Generated by Django 6.0.3 on 2026-04-03 11:12

import django.db.models.deletion
import horilla.registry.limiters
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horilla_core', '0012_alter_fieldpermission_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title')),
                ('method_title', models.CharField(editable=False, max_length=100, verbose_name='Method Title')),
                ('review_fields', models.JSONField(blank=True, default=list, verbose_name='Fields to Review')),
                ('notify_on_submission', models.BooleanField(default=False, verbose_name='Notify on Resubmission')),
                ('notify_on_approval', models.BooleanField(default=False, verbose_name='Notify on Approval')),
                ('notify_on_rejection', models.BooleanField(default=False, verbose_name='Notify on Rejection')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('model', models.ForeignKey(limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('reviews_models'), on_delete=django.db.models.deletion.CASCADE, to='horilla_core.horillacontenttype', verbose_name='Module')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Review Process',
                'verbose_name_plural': 'Review Processes',
            },
        ),
        migrations.CreateModel(
            name='ReviewCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('greater_than', 'Greater Than'), ('greater_than_equal', 'Greater Than or Equal'), ('less_than', 'Less Than'), ('less_than_equal', 'Less Than or Equal'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('exact', 'Equals'), ('gt', 'After'), ('lt', 'Before'), ('between', 'Between'), ('isnull', 'Is empty'), ('isnotnull', 'Is not empty'), ('icontains', 'Contains'), ('ne', 'Not Equals'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('logical_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3, verbose_name='Logical Operator')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='reviews.reviewprocess', verbose_name='Review Process')),
            ],
            options={
                'verbose_name': 'Review Condition',
                'verbose_name_plural': 'Review Conditions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approver_type', models.CharField(choices=[('user', 'User'), ('role', 'Role')], default='user', max_length=20, verbose_name='Approver Type')),
                ('approver_roles', models.ManyToManyField(blank=True, related_name='reviewses_as_role', to='horilla_core.role', verbose_name='Approver Roles')),
                ('approver_users', models.ManyToManyField(blank=True, related_name='reviewses_as_user', to=settings.AUTH_USER_MODEL, verbose_name='Approver Users')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='reviews.reviewprocess', verbose_name='Review Process')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Review Rule',
                'verbose_name_plural': 'Review Rules',
            },
        ),
        migrations.CreateModel(
            name='ReviewRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('greater_than', 'Greater Than'), ('greater_than_equal', 'Greater Than or Equal'), ('less_than', 'Less Than'), ('less_than_equal', 'Less Than or Equal'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('exact', 'Equals'), ('gt', 'After'), ('lt', 'Before'), ('between', 'Between'), ('isnull', 'Is empty'), ('isnotnull', 'Is not empty'), ('icontains', 'Contains'), ('ne', 'Not Equals'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('logical_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3, verbose_name='Logical Operator')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('review_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='reviews.reviewrule', verbose_name='Review Rule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Review Rule Condition',
                'verbose_name_plural': 'Review Rule Conditions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('review_fields_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Review Fields Snapshot')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('review_note', models.TextField(blank=True, verbose_name='Review Note')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horilla_core.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horilla_core.horillacontenttype', verbose_name='Content Type')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='reviews.reviewprocess', verbose_name='Review Process')),
                ('review_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='reviews.reviewrule', verbose_name='Review Rule')),
            ],
            options={
                'verbose_name': 'Review Job',
                'verbose_name_plural': 'Review Jobs',
                'ordering': ['status', '-created_at'],
                'unique_together': {('reviews', 'review_rule', 'content_type', 'object_id', 'assigned_to')},
            },
        ),
    ]
