# Generated by Django 6.0.3 on 2026-03-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_dashboard', '0004_alter_componentcriteria_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcomponent',
            name='chart_type',
            field=models.CharField(blank=True, choices=[('column', 'Column Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('funnel', 'Funnel'), ('bar', 'Bar Chart'), ('donut', 'Donut'), ('stacked_vertical', 'Stacked Vertical Chart'), ('stacked_horizontal', 'Stacked Horizontal Chart'), ('scatter', 'Scatter'), ('heatmap', 'Heat Map'), ('treemap', 'Tree Map'), ('area', 'Area Chart'), ('sankey', 'Sankey Chart'), ('radar', 'Radar Chart')], default='column', max_length=50, null=True, verbose_name='Chart Type'),
        ),
        migrations.AlterField(
            model_name='dashboardcomponent',
            name='columns',
            field=models.TextField(blank=True, null=True, verbose_name='Table Columns'),
        ),
        migrations.AlterField(
            model_name='dashboardcomponent',
            name='secondary_grouping',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Secondary Grouping'),
        ),
    ]
