# Generated by Django 6.0 on 2026-03-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_activity', '0003_alter_activity_created_at_alter_activity_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('waiting', 'Waiting on Someone'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
