# Generated by Django 6.0.3 on 2026-03-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_emailactivityscoring_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringcondition',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('greater_than', 'Greater Than'), ('greater_than_equal', 'Greater Than or Equal'), ('less_than', 'Less Than'), ('less_than_equal', 'Less Than or Equal'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('exact', 'Equals'), ('gt', 'After'), ('lt', 'Before'), ('between', 'Between'), ('isnull', 'Is empty'), ('isnotnull', 'Is not empty')], max_length=50, verbose_name='Operator'),
        ),
    ]
