# Generated by Django 6.0.3 on 2026-03-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_reports', '0004_alter_report_created_at_alter_report_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='chart_type',
            field=models.CharField(choices=[('column', 'Column Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('funnel', 'Funnel'), ('bar', 'Bar Chart'), ('donut', 'Donut'), ('stacked_vertical', 'Stacked Vertical Chart'), ('stacked_horizontal', 'Stacked Horizontal Chart'), ('scatter', 'Scatter Chart'), ('treemap', 'Treemap'), ('area', 'Area Chart'), ('heatmap', 'Heatmap'), ('sankey', 'Sankey'), ('radar', 'Radar Chart')], default='bar', max_length=20),
        ),
    ]
