# Generated by Django 6.0.3 on 2026-03-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_reports', '0005_alter_report_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='chart_value_field',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Value Field (Y-axis)'),
        ),
    ]
